/*TMODJS:{"version":4,"md5":"dae081b38efcbda3aaf26eb5e78ef789"}*/
template('formControlTextareaTemplate',function($data,$filename) {
'use strict';var $utils=this,$helpers=$utils.$helpers,$escape=$utils.$escape,listitem=$data.listitem,p=$data.p,data=$data.data,options=$data.options,flag=$data.flag,$out='';$out+='<textarea data-listitem="';
$out+=$escape(listitem);
$out+='" id="formitem-';
$out+=$escape(p);
$out+='" class="formitem-control formitem-input ';
$out+=$escape(data.classname);
$out+='" style="';
$out+=$escape(data.style);
$out+='" ';
$out+=$escape(options.status);
$out+=' placeholder="';
$out+=$escape(data.placeholder);
$out+='" data-flag="';
$out+=$escape(flag);
$out+='" ';
$out+=$escape(data.validation);
$out+=' ';
$out+=$escape(data.disabled);
$out+=' ';
$out+=$escape(data.attr);
$out+=' data-order="';
$out+=$escape(data.order);
$out+='" type="';
$out+=$escape(data.control);
$out+='">';
$out+=$escape(data.value);
$out+='</textarea>';
return new String($out);
});